# User configuration

# Default to color LS if available on OSX
if [[ "$OSTYPE" == darwin* ]]; then
  ls -G . &>/dev/null && alias ls='ls -G'
fi

if [[ `whoami` = "root" ]]; then
  CONFDIR=$ZDOTDIR
else
  CONFDIR=$HOME
fi

if [[ -f $CONFDIR/cfg/zsh/yukeake.zsh-theme ]]; then
  source $CONFDIR/cfg/zsh/yukeake.zsh-theme
fi

if [[ -f $CONFDIR/cfg/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source $CONFDIR/cfg/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [[ -f $CONFDIR/cfg/fzf/fzf.zsh ]]; then
  source $CONFDIR/cfg/fzf/fzf.zsh
fi

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias cv="curl -s 'https://corona-stats.online/?top=5&minimal=true' | head -n 7"
alias ww="curl -ks 'wttr.in/?2nq'"

alias gl="git log --oneline"
alias gl5="git log --oneline -5"
alias gl10="git log --oneline -10"

alias go2autoscale="cd /Users/brent/Projects/Grid/GridDeployment/CNext.internal/resources/deployment/Cloud/Grid/default/data/OperationsAgent/scripts/Grid"

if [[ -x /usr/local/bin/exa ]]; then
  alias ls="exa -g --group-directories-first"
fi

